spring:
  application:
    name: SpringProject
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test_schema
    username: postgres
    password: Nol0511ok*
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      enable_lazy_load_no_trans: false
    show-sql: true
    open-in-view: false
#  security:
#    user:
#      name: user
#      password: 123

springdoc:
  api-docs:
    path: /swagger-ui
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html

app:
  integration:
    currency-dictionary:
      client:
        url: https://www.cbr-xml-daily.ru/daily_json.js

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE