spring:
  application:
    name: SpringProject
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test_schema
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: false
    show-sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /swagger-ui
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE